name: ci
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'master'
    paths:
      - 'backend/**/*'
      - 'protocol/**/*'
      - 'state/**/*'
      - '.dockerignore'
      - 'Dockerfile.backend'
      - 'fly.toml'
      - 'pnpm-lock.yaml'
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: deploy backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
